version: "3"
services:
    web:
        build: .
        volumes:
            - ./pagina_web_php:/var/www/html
        ports:
            - 80:80
    db:
        image: mysql
        volumes:
            - ./db_data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: repodocker_db
        ports:
            - 3306:3306

